### ISSUE TITLE
Instruction on how to run and installation. 

### ISSUE THREAD

**Issue by npatel22526** [zilinli1988/SCANG#1]
Hello, 

I went through the SCANG paper and interested in trying the R-packages for GWAS. Can you please provide instruction for installation and example usage. Specifically, how should I format input files. 

Best,
Nick

**Comment by zilinli1988** [comment]
Hi Nick,

For usage, please see the attached Reference manual of SCANG in the attachment. You could also find examples SCANG/vignettes/SCANG.Rmd in GitHub (SCANG/vignettes/SCANG.Rmd). 

For installation, you could try the following code: 

install.packages("remotes")
library(remotes)
remotes::install_github("smgogarten/GENESIS")
remotes::install_github("zilinli1988/SCANG")

For the input file, we need genotype, phenotype and covariates saved in R. If you want to control for relatedness, SCANG further require the GRM or kinship matrix for input. 

If you have further questions about SCANG, please contact me. 

Sincerely,
Zilin



发件人: Nihir
发送时间: Tuesday, August 20, 2019 2:59 PM
收件人: zilinli1988/SCANG
抄送: Subscribed
主题: [zilinli1988/SCANG] Instruction on how to run and installation. (#1)

Hello,
I went through the SCANG paper and interested in trying the R-packages for GWAS. Can you please provide instruction for installation and example usage. Specifically, how should I format input files.
Best,
Nick

**Comment by npatel22526** [comment]
Dear Zilin, 
Thank you for quick response. 
Sorry I can't find the attachment
Also For installation I am getting error "clang: error: unsupported option '-fopenmp'. Any suggestion ?

**Comment by zilinli1988** [comment]
HI Nick,

I guess you might use the macOS. Could you please try the following solution https://daijiang.name/en/2017/06/21/fopenmp-option-of-clang-error/ ? If it does not work, please let me know.

Sincerely,
Zilin 



发件人: Nihir
发送时间: Tuesday, August 20, 2019 4:17 PM
收件人: zilinli1988/SCANG
抄送: Zilin Li; Comment
主题: Re: [zilinli1988/SCANG] Instruction on how to run and installation.(#1)

Dear Zilin,
Thank you for quick response. For installation I am getting error "clang: error: unsupported option '-fopenmp'. Any suggestion ?

**Comment by npatel22526** [comment]
Great !! It worked but I am having trouble understanding SCANG/vignettes/SCANG.Rmd. 
I have 3 matrix from plink for which I want to perform burden testing. I am also following 
https://content.sph.harvard.edu/xlin/dat/SCANG-manual.pdf

**Plink genotype file** : I can convert this to n*p matrix 
**Phenotype file** : I have multiple phenotype arranged in column. If in SCAN_B works for single phenotype at a time I can easily convert this to vector. According to manual the phenotype variable is vector , does that mean I have to subset and sort my genotype matrix  such that in only contains exact same number of row as length of phenotype ?
**Co-variate matrix**  : Again does it need to have exact same number rows as genotype file , or samples can be specified ? 

Thanks for all your help in advance. 
Nick

**Comment by zilinli1988** [comment]
Hi Nick,

Yes. I think so. Sorry for the inconvenience. I will try to solve these problems in the next version of SCANG. 

Sincerely,
Zilin

发件人: Nihir
发送时间: Thursday, August 22, 2019 10:23 AM
收件人: zilinli1988/SCANG
抄送: Zilin Li; Comment
主题: Re: [zilinli1988/SCANG] Instruction on how to run and installation.(#1)

Great !! It worked but I am having trouble understanding SCANG/vignettes/SCANG.Rmd.
I have 3 matrix from plink for which I want to perform burden testing. I am also following
https://content.sph.harvard.edu/xlin/dat/SCANG-manual.pdf
Plink genotype file : I can convert this to n*p matrix
Phenotype file : I have multiple phenotype arranged in column. If in SCAN_B works for single phenotype at a time I can easily convert this to matrix. According to manual the phenotype variable is vector , does that mean I have to subset and sort my genotype matrix such that in only contains exact same number of row as length of phenotype ?
Co-variate matrix : Again does it need to have exact same number row as genotype file , or samples can be specified ?
Thanks for all your help in advance.
Nick

**Comment by npatel22526** [comment]
Thanks for continuous support. 
Pardon me if below question is too naive, I am just getting my feet wet with statistics in R. 
Can you please explain below lines from SCANG.Rmd. 
`obj_nullmodel <- fit_null_glm(phenotype~-1+X,data=phenotypedata,family=gaussian(link = "identity"))`

I see that we are creating formula for null model but I am having hard time follow the formula, but what does phenotype~-1 means  ?

**Comment by zilinli1988** [comment]
Hi Nick,

Phenotype~-1 means that this is no intercept in the model. In the simulation example, we did not have the intercept in the true model, so we did not include it in the application. I think you do not need the “-1” in your application. 

Sincerely,
Zilin

**Comment by npatel22526** [comment]
Really appreciate your quick response,  I understand now. Couple last thing I want to confirm before running my analysis 
1. Any Suggestion on how to set Lmax and Lmin ? 
2. And can you verify the correct way to form null model object ? 

`obj_nullmodel <- fit_null_glm(phenotype~+coVar,data=phenotypedata,family=binomial(link = "logit"))`
                                                                   **Or**
`obj_nullmodel <- fit_null_glm(phenotype~coVar,data=phenotypedata,family=binomial(link = "logit"))`

Where, 
- Genotypes are stored in **genotype** data frame where  each row is sample ID and Column is SNP genotypes
- I have binary phenotype stored in dataframe  **phenotypedata**
- 10PCs, Age and Sex  co-variates are stored in  **coVar**

Sincerely,
Nick

**Comment by zilinli1988** [comment]
Hi Nick,

1. If you are analyzing rare variants, I recommend you to use Lmin=40 and Lmax=200. If you are analyzing common variants, I think you could first try Lmin=10 or 20 and Lmax=50 to 100.
2. I think it is the second model.

Sincerely,
Zilin

**Comment by npatel22526** [comment]
Perfect ! Thanks a ton.
