### ISSUE TITLE
Running time and MAF

### ISSUE THREAD

**Issue by npatel22526** [zilinli1988/SCANG#2]
Hello, 

I was trying to run SCANG for about 3,000 combined cases and controls,  with about 150K variants. But it is taking too long generate results. 
Here are the commands I used. 

```
obj_nullmodel <- fit_null_glm(ASD~co_var,data=phenotypedata,family=binomial(link = "logit")
res_lm <- SCANG(genotype,obj_nullmodel,Lmin=40,Lmax=200,filter=1,f=0,rare_maf_cutoff=1)

```
The  default is to output only significant values  and I wanted P-values for all windows scanned by SCANG. So I set **filter=1** . It seems to be happening only when I set the filter to 1. 

Also how MAF is calculated ? I have a matrix that is already filtered for MAF and then sub sampled to retain only some of the samples, is SCANG recalculating allele frequency and applying the filter ?  

Thanks, 
Nick

**Comment by zilinli1988** [comment]
Hi Nick,

If you set filter=1, which means that you need to calculate 9.6M SKAT p-values and it make a long time. In your case, I recommend to set filter=1e-3. 

The parameter filter is for p-value filter, which do nothing for the MAF.

Sincerely,
Zilin 


From: Nihir
Sent: Friday, August 30, 2019 3:30 PM
To: zilinli1988/SCANG
Cc: Subscribed
Subject: [zilinli1988/SCANG] Running time and MAF (#2)

Hello,
I was trying to run SCANG for about 3,000 combined cases and controls, with about 150K variants. But it is taking too long generate results.
Here are the commands I used.
obj_nullmodel <- fit_null_glm(ASD~co_var,data=phenotypedata,family=binomial(link = "logit")
res_lm <- SCANG(genotype,obj_nullmodel,Lmin=40,Lmax=200,filter=1,f=0,rare_maf_cutoff=1)

The default is to output only significant values and I wanted P-values for all windows scanned by SCANG. So I set filter=1 . It seems to be happening only when I set the filter to 1.
Also how MAF is calculated ? I have a matrix that is already filtered for MAF and then sub sampled to retain only some of the samples, is SCANG recalculating allele frequency and applying the filter ?
Thanks,
Nick

**Comment by npatel22526** [comment]
Thank you for quick response. filter=1e-3 make sense. 
Regarding MAF just to clarify I am refereeing to "rare_maf_cutoff ' . How is it calculated ?

**Comment by zilinli1988** [comment]
When you set rare_maf_cutoff=1, SCANG will keep all the SNVs.

Sent from Mail for Windows 10

**Comment by npatel22526** [comment]
Ok great thanks.
