### ISSUE TITLE
Continuous P-value and Per chromosome Analysis

### ISSUE THREAD

**Issue by npatel22526** [zilinli1988/SCANG#3]
Hello, 

With all of your previous help I was successfully be able to run the SCANG. But I have two queries regarding output. 
In the output, all the P-values < 5E10-4 are assigned as 0 , is it possible to get more continuous P-values ?  I am curious as in results I have  -log(p-value) range from 22-75 but for all of them P-values are 0.   
It takes quite longer to run it on entire genome so I ended up running SCANG per chromosome, how would it affects P-values ? 

Best, 
Nick

**Comment by zilinli1988** [comment]
Hi Nick,

1. In SCANG, the fist column is the region-based p-value and the last column is the genome-wide p-value (adjusted p-value that accounting for multiple comparison). We calculate the genome-wide p-value using 2,000 Monte Carlo simulation and it is accurate at the 0.05 or 0.01 level. If you see the genome-wide p-value equals to 0, then it must be smaller than 0.001. I feel sorry that the current version of SCANG could not give an accurate empirical genome-wide p-value below level 0.001.
2. If you run SCANG by chromosome, then you need another step to calculate the genome-wide threshold and the genome-wide p-value. Now the last column of SCANG in your case is the chromosome-wide p-value. I think you can do it like this:
(1) Generate an empty matrix: 
            emthr <- c() 
(2) For each chromosome, get the vector of Monte Carlo simulation sample for generating the empirical threshold and then save them into the matrix, 
                 emthr_chr <- SCANG_results$SCANG_O_thres_boot
emthr <- rbind(emthr,emthr_chr)
(3) Calculate the genome-wide sample for generating the empirical threshold,
              emthr_genome <- apply(emthr,2,max)
     (4) Calculate the genome-wide threshold at level alpha.
		           thr <- quantile(emthr_genome,1-alpha)

If you have any other question, please feel free to contact me.

Sincerely,
Zilin


发件人: Nihir
发送时间: Wednesday, September 11, 2019 2:27 PM
收件人: zilinli1988/SCANG
抄送: Subscribed
主题: [zilinli1988/SCANG] Continuous P-value and Per chromosome Analysis(#3)

Hello,
With all of your previous help I was successfully be able to run the SCANG. But I have two queries regarding output.
In the output, all the P-values < 5E10-4 are assigned as 0 , is it possible to get more continuous P-values ? I am curious as in results I have -log(p-value) range from 22-75 but for all of them P-values are 0.
It takes quite longer to run it on entire genome so I ended up running SCANG per chromosome, how would it affects P-values ?
Best,
Nick

**Comment by npatel22526** [comment]
Thanks for Quick response. 

2nd question I understood very well. 

For 1st, I am little confused,  so If I increase the Monte Carlo simulation would it be possible to get accurate P-values below 0.001 or it's the limitation of current version of SCANG and can not be obtained ? 
Nick

**Comment by zilinli1988** [comment]
Hi Nick,

Sorry for the confusion. You are right. If you increase the Monte Carlo simulation, you would be able to get accurate p-values. You can set the parameter times in the null model function, fit_null_glm and fit_null_glmmkin. The default is 2000.

Sincerely,
Zilin


发件人: Nihir
发送时间: Wednesday, September 11, 2019 3:29 PM
收件人: zilinli1988/SCANG
抄送: Zilin Li; Comment
主题: Re: [zilinli1988/SCANG] Continuous P-value and Per chromosomeAnalysis (#3)

Thanks for Quick response.
#2 I understood very well.
For #1 I am little confused, so If I increase the Monte Carlo simulation would it be possible to get accurate P-values below 0.001 or it's the limitation of current version of SCANG and can not be obtained ?
Nick

**Comment by npatel22526** [comment]
Awesome ! Thank you very much.

**Comment by npatel22526** [comment]
Hello, 
It takes huge time to run the analysis with higher numbers if Monte Carlo simulation, curious what i how the P-value and Monte Carlo simulation are connected ,  What I am interested is to achieve P-values of 10e-10 , what would be the minimum number of stimulation required to achieve the P-value ? 

Best, 
Nick

**Comment by zilinli1988** [comment]
Hi Nick,

Sorry for reply late. I think your question is how to get the genome-wide p-value of the region with region-based p-value at 1E-10 level. You could set lower filter value to save time. Could you please kindly tell me the threshold of 0.05? Then we could discuss how to set the filter value and simulation times.

Sincerely,
Zilin

发件人: Nihir
发送时间: Monday, September 23, 2019 10:51 AM
收件人: zilinli1988/SCANG
抄送: Zilin Li; Comment
主题: Re: [zilinli1988/SCANG] Continuous P-value and Per chromosomeAnalysis (#3)

Hello,
It takes huge time to run the analysis with higher numbers if Monte Carlo simulation, curious what i how the P-value and Monte Carlo simulation are connected , What I am interested is to achieve P-values of 10e-10 , what would be the minimum number of stimulation required to achieve the P-value ?
Best,
Nick

**Comment by npatel22526** [comment]
Hello Zilin, 

To reiterate , what I am trying to achieve is more accurate P-values.
My lowest P-value was 0.0005 and then everything below was 0, I want to know what are those  Pvalue=0 means , are they 10-E6 or they 10-E60. 
My current parameters are below 

Number co-variables = 4 
family <- "binomial"
Lmax <- 200
Lmin <- 10
filter <- 0.0001
rare_maf_cutoff=1 # Because data is already filtered
alpha=1 # Because I am interested in all of the P-values worst to best 
times = ? # number of  Monte Carlo simulation that I am trying to figure

Thanks, 
Nick

**Comment by zilinli1988** [comment]
Hi Nick,

I’m still confusing. The first column of the SCANG output is just -log(pvalue). Could you please show me an example of your results? If the first column is 0, then that means that there is no signal region.

Sincerely,
Zilin


发件人: Nihir
发送时间: Thursday, September 26, 2019 8:22 AM
收件人: zilinli1988/SCANG
抄送: Zilin Li; Comment
主题: Re: [zilinli1988/SCANG] Continuous P-value and Per chromosomeAnalysis (#3)

Hello Zilin,
To reiterate , what I am trying to achieve is more accurate P-values.
My lowest P-value was 0.0005 and then everything below was 0, I want to know what are those Pvalue=0 means , are they 10-E6 or they 10-E60.
My current parameters are below
Number co-variables = 4
family <- "binomial"
Lmax <- 200
Lmin <- 10
filter <- 0.0001
rare_maf_cutoff=1 # Because data is already filtered
alpha=1 # Because I am interested in all of the P-values worst to best
times = ? # number of Monte Carlo simulation that I am trying to figure
Thanks,
Nick

**Comment by npatel22526** [comment]
Hello Zilin,


The first column is not zero. Attached is one of the example of output


> res_lm$SCANG_O_res
           [,1]   [,2]   [,3]   [,4]
  [1,] 42.35030 205739 205748 0.0000
  [2,] 27.13517 205638 205647 0.0000
  [3,] 22.92851 553384 553393 0.0000
  [4,] 20.99632  29297  29306 0.0005
  [5,] 20.19205 134617 134726 0.0015
  [6,] 19.67713  27933  27942 0.0015
  [7,] 18.41144 143182 143191 0.0055
  [8,] 17.83010 547781 547815 0.0115
  [9,] 17.18982 303784 303798 0.0225
 [10,] 17.18617 621150 621169 0.0225



Here, I want to know what are "Accurate" P-values for row1 to row3


Nick

________________________________

**Comment by zilinli1988** [comment]
Hi Nick,

The region-based p-value of the first region is exp(-42.35030)=4.05E-19. The genome-wide p-value might be quite small, but only guarantee to be smaller than 0.005.

Sincerely,
Zilin

发件人: Nihir
发送时间: Thursday, September 26, 2019 2:33 PM
收件人: zilinli1988/SCANG
抄送: Zilin Li; Comment
主题: Re: [zilinli1988/SCANG] Continuous P-value and Per chromosomeAnalysis (#3)

Hello Zilin, 


The first column is not zero. Attached is one of the example of output 


> res_lm$SCANG_O_res 
[,1] [,2] [,3] [,4] 
[1,] 42.35030 205739 205748 0.0000 
[2,] 27.13517 205638 205647 0.0000 
[3,] 22.92851 553384 553393 0.0000 
[4,] 20.99632 29297 29306 0.0005 
[5,] 20.19205 134617 134726 0.0015 
[6,] 19.67713 27933 27942 0.0015 
[7,] 18.41144 143182 143191 0.0055 
[8,] 17.83010 547781 547815 0.0115 
[9,] 17.18982 303784 303798 0.0225 
[10,] 17.18617 621150 621169 0.0225 



Here, I want to know what are "Accurate" P-values for row1 to row3 


Nick 

________________________________

**Comment by npatel22526** [comment]
Exactly how do I change the 0.0005 to say  0.0000005 .?

________________________________

**Comment by zilinli1988** [comment]
One possible solution is to set filter=1e-07 and time=20000, and see the results of the top three region.


发件人: Nihir
发送时间: Thursday, September 26, 2019 2:39 PM
收件人: zilinli1988/SCANG
抄送: Zilin Li; Comment
主题: Re: [zilinli1988/SCANG] Continuous P-value and Per chromosomeAnalysis (#3)

Exactly how do I change the 0.0005 to say 0.0000005 .? 

________________________________

**Comment by npatel22526** [comment]
Thanks for quick responses. But the combination didn't really helped , lowest P-value I am getting is 10E-5 and run time increased significantly to the point that it almost not practical.

**UPDATE : I also tried 60K stimulation and still lowest P-value I am getting is 10E-5**

I try understanding the filter option from paper but it's not clear how it effects the results. Can you please elaborate what is the filter option is doing , how it affects the outcome and number of windows ? As I noted that increasing filter & time decreases number of windows.

Nihir

**Comment by npatel22526** [comment]
> emthr

The script only provides the genome wide -log(P-value) threshold , how to obtain P-values ?
